name: Render

on:
  workflow_dispatch:
  push:
    paths:
      - input.dot

jobs:
  render-svg:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get -y install graphviz

      - uses: actions/checkout@v2

      - name: render
        run: |
          dot -Tsvg input.dot > output.svg

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add output.svg
          git commit -m "update output.svg"
          git push origin $GITHUB_REF
